import { a as DEFAULT_USER_CHAR_LIMIT, c as name, i as DEFAULT_REVIEW_MAX_ITERATIONS, n as DEFAULT_MEMORY_CHAR_LIMIT, o as apply, r as DEFAULT_NUDGE_INTERVAL, s as inject, t as Config } from "./src-BPklm9EU.js";
export { Config, DEFAULT_MEMORY_CHAR_LIMIT, DEFAULT_NUDGE_INTERVAL, DEFAULT_REVIEW_MAX_ITERATIONS, DEFAULT_USER_CHAR_LIMIT, apply, inject, name };
